### ISSUE TITLE
Nx typedoc plugin invalid options configuration

### ISSUE THREAD

**Issue by Fuco1** [enio-ireland/enio#46]
It seems that the path to the `typedoc.json` must be prefixed with the project prefix (as if relative to the root of the repo), otherwise typedoc complains it can't find the configuration

```
"typedoc": {
      "executor": "@enio.ai/typedoc:typedoc",
      "options": {
        "options": "typedoc.json"   /// <<< prefix with libs/ds/ for library project "ds"
      },
      "configurations": {}
    }
```

**Comment by AndrewRedican** [comment]
@Fuco1 I cannot reproduce this issue.

How this works is like so:

For any target project,

```
    "options": {
        "options": "typedoc.json"
     },
```

in that project's `project.json` file, refers to a `typedoc.json` file in the project's directory, _not_ the workspace.

Each project will have its own documentation configuration in the `typedoc.json` file. This is by design,  as projects can come in many different architectures, etc, so it is wise to keep each to its own rather than have them shared at the workspace level.
